micronaut:
  application:
    name: oda-news-service
  security:
    token:
      bearer:
        enabled: true
      cookie:
        enabled: true
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${JWKS_URI}
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
flyway:
  datasources:
    default:
      enabled: true
      schemas: 'news'
      default-schema: 'news'
endpoints:
  prometheus:
    sensitive: false
  metrics:
    sensitive: false
datasources:
  default:
    schema: 'news'
