micronaut:
  application:
    name: oda-news-service
  security:
    token:
      bearer:
        enabled: true
      cookie:
        enabled: true
      jwt:
        signatures:
          jwks:
            keycloak:
              url: https://auth.oda.digital/realms/ODA/protocol/openid-connect/certs
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
flyway:
  datasources:
    default:
      enabled: true
endpoints:
  prometheus:
    sensitive: false
