name: Release

on:
  push:
    branches: ["main"]

permissions: write-all

jobs:

  build-and-push:
    uses: 'OpenDonationAssistant/oda-k3s-specs/.github/workflows/build_with_npm.yml@main'
    needs: build-and-push
    secrets: inherit
    with:
      service: news-service
      version: '${{ github.RUN_NUMBER }}'

  update-deployment-configuration:
    uses: 'OpenDonationAssistant/oda-k3s-specs/.github/workflows/update_version.yml@main'
    needs: build-and-push
    secrets: inherit
    with:
      service: news-service
      version: '${{ github.RUN_NUMBER }}'

  deploy:
    uses: 'OpenDonationAssistant/oda-k3s-specs/.github/workflows/deploy.yml@main'
    needs: update-deployment-configuration
    secrets: inherit
    with:
      service: news-service
      version: '${{ github.RUN_NUMBER }}'
