name: Release

on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/setup-node@v3
      with:
        node-version: "20"

    - name: Checkout ansible scripts
      uses: actions/checkout@v4
      with:
        repository: "OpenDonationAssistant/oda-k3s-specs"
        path: "scripts"

    - name: Update version
      uses: teunmooij/yaml@v1
      with:
        from-file: 'scripts/service-news.yaml'
        to-file: 'scripts/service-news.yaml'
        merge: '{ "spec.template.spec.containers[0].image": "ghcr.io/opendonationassistant/oda-news-service:${{ github.RUN_NUMBER }}" }'

    - run: cat scripts/service-news.yaml

    - name: Commit & Push changes
      uses: actions-js/push@master
      run: | 
        cd scripts
        git commit -am "[skip ci] up version"
        git remote set-url origin https://${{ secrets.PUSH_TOKEN }}@github.com/OpenDonationAssistant/oda-k3s-specs
        git push

    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dpackaging=native-image -DskipTests

    - run: npm install
      working-directory: "target/generated-sources/openapi/"

    - uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        registry: "https://npm.pkg.github.com"
        package: "target/generated-sources/openapi/"

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/opendonationassistant/oda-news-service:${{ github.RUN_NUMBER }}

    - name: Deploying new version
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: sh ~/update_news_service.sh ${{ github.RUN_NUMBER }}
